#!/bin/bash

# Use to pipe text selection in Vim to mysql. 

# :.w ! db dbname

# or save db name in .pipedb in working dir and ...

# :.w ! db 

if [[ -s .db ]]; then
  db=`cat .db`
else
  db=$1
fi
mysql -uroot $db -t
